const mockData = {
  featuredArticles: [
    {
      id: 'featured-1',
      title: 'The Future of Business: AI and Automation',
      summary: 'Exploring how artificial intelligence and automation are set to reshape industries, from manufacturing to finance. This article provides a deep dive into the technologies driving this change and what it means for the workforce of tomorrow.',
      author: 'Jane Doe',
      date: 'Aug 1, 2025',
      image: 'https://placehold.co/1200x600/A7C7E7/ffffff?text=AI+and+Automation',
      category: 'Technology',
      readTime: '8 min read',
    },
    {
      id: 'featured-2',
      title: 'Marketing in the Digital Age: Strategies for Success',
      summary: 'A comprehensive guide to digital marketing, covering everything from SEO and content creation to social media and email campaigns. Learn how to build a powerful online presence and connect with your target audience.',
      author: 'John Smith',
      date: 'Jul 28, 2025',
      image: 'https://placehold.co/1200x600/EBF4F8/333333?text=Digital+Marketing',
      category: 'Marketing',
      readTime: '10 min read',
    },
    {
      id: 'featured-3',
      title: 'Financial Wellness: A Guide to Smart Investing',
      summary: 'Demystifying the world of personal finance. This article breaks down smart investment strategies for beginners, including tips on budgeting, saving, and building a diversified portfolio for long-term growth.',
      author: 'Emily White',
      date: 'Jul 25, 2025',
      image: 'https://placehold.co/1200x600/63b3ed/ffffff?text=Smart+Investing',
      category: 'Finance',
      readTime: '6 min read',
    },
  ],
  categories: [
    { name: 'Technology', count: 12 },
    { name: 'Marketing', count: 8 },
    { name: 'Finance', count: 15 },
    { name: 'Startups', count: 5 },
    { name: 'Business', count: 20 },
    { name: 'Productivity', count: 9 },
  ],
  articles: [ // Latest Articles
    {
      id: 'latest-1',
      title: 'The Rise of Remote Work: What It Means for Office Culture',
      summary: 'Examining the pros and cons of remote work and its impact on team collaboration and company culture.',
      author: 'Sarah Chen',
      date: 'Aug 10, 2025',
      image: 'https://placehold.co/800x400/90b5e4/333333?text=Remote+Work',
      category: 'Business',
      readTime: '7 min read',
    },
    {
      id: 'latest-2',
      title: 'Building a Strong Personal Brand on Social Media',
      summary: 'Tips and tricks for leveraging social media platforms to build a compelling personal brand that attracts opportunities.',
      author: 'David Lee',
      date: 'Aug 8, 2025',
      image: 'https://placehold.co/800x400/b1d2f0/333333?text=Personal+Brand',
      category: 'Marketing',
      readTime: '5 min read',
    },
    {
      id: 'latest-3',
      title: 'The Psychology of Consumer Behavior: What Drives Purchases',
      summary: 'A look into the psychological principles that influence consumer decisions and how businesses can use them ethically.',
      author: 'Maria Garcia',
      date: 'Aug 6, 2025',
      image: 'https://placehold.co/800x400/92c6f3/ffffff?text=Consumer+Behavior',
      category: 'Marketing',
      readTime: '9 min read',
    },
    {
      id: 'latest-4',
      title: 'Five Habits of Highly Effective Entrepreneurs',
      summary: 'Learn from successful entrepreneurs and discover the key habits that contribute to their success.',
      author: 'Michael Brown',
      date: 'Aug 4, 2025',
      image: 'https://placehold.co/800x400/a3d1e6/333333?text=Entrepreneurs',
      category: 'Startups',
      readTime: '6 min read',
    },
    {
      id: 'latest-5',
      title: 'Blockchain Beyond Crypto: New Applications and Innovations',
      summary: 'Exploring the non-financial applications of blockchain technology, including supply chain management and voting systems.',
      author: 'Olivia Wilson',
      date: 'Aug 2, 2025',
      image: 'https://placehold.co/800x400/b0d6f5/ffffff?text=Blockchain',
      category: 'Technology',
      readTime: '8 min read',
    },
    {
      id: 'latest-6',
      title: 'Understanding the Gig Economy and its Impact',
      summary: 'A deep dive into the gig economy, its benefits, challenges, and the future of work.',
      author: 'Liam Jones',
      date: 'Jul 30, 2025',
      image: 'https://placehold.co/800x400/95cae7/333333?text=Gig+Economy',
      category: 'Business',
      readTime: '7 min read',
    },
  ],
  trendingArticles: [ // Mock articles for the trending tab
    {
      id: 'trending-1',
      title: 'Top 10 Productivity Hacks for Your Business',
      summary: 'Boost your team’s efficiency and output with these proven techniques and tools for a more productive workplace.',
      author: 'Anna Peterson',
      date: 'Jul 15, 2025',
      image: 'https://placehold.co/800x400/d9f1b9/333333?text=Productivity+Hacks',
      category: 'Productivity',
      readTime: '5 min read',
    },
    {
      id: 'trending-2',
      title: 'The Art of Storytelling in Marketing',
      summary: 'Discover how to craft compelling narratives that resonate with your audience and build lasting brand loyalty.',
      author: 'Chris Evans',
      date: 'Jun 22, 2025',
      image: 'https://placehold.co/800x400/c7e9d7/333333?text=Storytelling',
      category: 'Marketing',
      readTime: '8 min read',
    },
    {
      id: 'trending-3',
      title: 'Sustainable Business Practices: A Guide for Modern Companies',
      summary: 'Learn how integrating eco-friendly strategies can not only benefit the planet but also improve your bottom line.',
      author: 'Nicole Adams',
      date: 'May 10, 2025',
      image: 'https://placehold.co/800x400/bde0da/333333?text=Sustainable+Business',
      category: 'Business',
      readTime: '12 min read',
    },
  ],
};
export default mockData; 